export const TOPIC_LABELS: Record<string, string> = {
  html_semantics: "Семантика HTML",
  forms: "Формы",
  attributes: "Атрибуты",
  block_inline: "Блочные и строчные",
  selectors: "CSS-селекторы",
  specificity: "Специфичность",
  box_model: "Box model",
  flexbox: "Flexbox",
  grid: "Grid",
  position: "Position",
  responsive: "Responsive design",
  media_queries: "Media queries",
  pseudo: "Псевдоклассы/элементы",
  cascade: "Каскад и наследование",
  units: "Единицы измерения",
  js_variables: "JS: переменные",
  js_types: "JS: типы данных",
  js_conversion: "JS: преобразование типов",
  js_operators: "JS: операторы",
  js_comparison: "JS: сравнения",
  js_conditions: "JS: условия",
  js_logic: "JS: логические операторы",
  js_loops: "JS: циклы",
  js_switch: "JS: switch",
  js_functions: "JS: функции",
  js_arrow_functions: "JS: стрелочные функции",
  js_scope: "JS: область видимости",
  js_hoisting: "JS: hoisting",
  js_arrays: "JS: массивы",
  js_objects: "JS: объекты",
  js_this: "JS: this",
  js_prototypes: "JS: прототипы",
  js_constructor_functions: "JS: функции-конструкторы",
  js_closures: "JS: замыкания",
  js_recursion: "JS: рекурсия",
  js_binary_search: "Алгоритмы: бинарный поиск",
  js_classes: "JS: классы",
  js_strings: "JS: строки",
  js_errors: "JS: ошибки",
  js_builtin: "JS: встроенные объекты",
  js_collections: "JS: коллекции",
  js_dom: "JS: DOM",
  js_events: "JS: события",
  js_async: "JS: асинхронность"
};

export const TOPIC_LINKS: Record<string, string> = {
  html_semantics: "https://developer.mozilla.org/en-US/docs/Glossary/Semantics",
  forms: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms",
  attributes: "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes",
  block_inline: "https://developer.mozilla.org/en-US/docs/Glossary/Block-level_content",
  selectors: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors",
  specificity: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Specificity",
  box_model: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Box_model",
  flexbox: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox",
  grid: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Grids",
  position: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Positioning",
  responsive: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design",
  media_queries: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries",
  pseudo: "https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes",
  cascade: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts",
  units: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Values_and_units",
  js_variables: "https://learn.javascript.ru/variables",
  js_types: "https://learn.javascript.ru/types",
  js_conversion: "https://learn.javascript.ru/type-conversions",
  js_operators: "https://learn.javascript.ru/operators",
  js_comparison: "https://learn.javascript.ru/comparison",
  js_conditions: "https://learn.javascript.ru/ifelse",
  js_logic: "https://learn.javascript.ru/logical-operators",
  js_loops: "https://learn.javascript.ru/while-for",
  js_switch: "https://learn.javascript.ru/switch",
  js_functions: "https://learn.javascript.ru/function-basics",
  js_arrow_functions: "https://learn.javascript.ru/arrow-functions-basics",
  js_scope: "https://metanit.com/web/javascript/3.5.php",
  js_hoisting: "https://metanit.com/web/javascript/3.10.php",
  js_arrays: "https://metanit.com/web/javascript/2.8.php",
  js_objects: "https://metanit.com/web/javascript/4.1.php",
  js_this: "https://metanit.com/web/javascript/4.2.php",
  js_prototypes: "https://metanit.com/web/javascript/4.8.php",
  js_constructor_functions: "https://learn.javascript.ru/constructor-new",
  js_closures: "https://learn.javascript.ru/closure",
  js_recursion: "https://learn.javascript.ru/recursion",
  js_binary_search: "https://www.my-interview.tech/0000-Навигация/001-Frontend/003-JSCore#алгоритмы",
  js_classes: "https://metanit.com/web/javascript/5.1.php",
  js_strings: "https://metanit.com/web/javascript/7.1.php",
  js_errors: "https://metanit.com/web/javascript/8.1.php",
  js_builtin: "https://metanit.com/web/javascript/9.1.php",
  js_collections: "https://metanit.com/web/javascript/10.3.php",
  js_dom: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/DOM_scripting",
  js_events: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Events",
  js_async: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Introducing"
};

export const VACANCY_KEYWORDS: Array<{ keyword: string; topics: string[] }> = [
  { keyword: "html", topics: ["html_semantics", "attributes"] },
  { keyword: "css", topics: ["selectors", "cascade", "units"] },
  { keyword: "bem", topics: ["selectors"] },
  { keyword: "flexbox", topics: ["flexbox"] },
  { keyword: "grid", topics: ["grid"] },
  { keyword: "адаптив", topics: ["responsive", "media_queries"] },
  { keyword: "семантик", topics: ["html_semantics"] },
  { keyword: "scss", topics: ["cascade"] },
  { keyword: "git", topics: ["attributes"] },
  {
    keyword: "javascript",
    topics: ["js_variables", "js_types", "js_functions", "js_arrays", "js_objects", "js_conditions", "js_loops"]
  },
  { keyword: "js", topics: ["js_variables", "js_types", "js_functions"] },
  { keyword: "урок", topics: ["js_functions"] },
  { keyword: "рекурс", topics: ["js_recursion"] },
  { keyword: "бинарн", topics: ["js_binary_search"] },
  { keyword: "замыкан", topics: ["js_closures", "js_scope"] },
  { keyword: "прототип", topics: ["js_prototypes"] },
  { keyword: "функция-конструктор", topics: ["js_constructor_functions"] },
  { keyword: "функции-конструкторы", topics: ["js_constructor_functions"] },
  { keyword: "конструктор", topics: ["js_constructor_functions", "js_classes"] },
  { keyword: "dom", topics: ["js_dom"] },
  { keyword: "event", topics: ["js_events"] },
  { keyword: "promise", topics: ["js_async"] },
  { keyword: "async", topics: ["js_async"] },
  { keyword: "форм", topics: ["forms"] },
  { keyword: "position", topics: ["position"] },
  { keyword: "media quer", topics: ["media_queries"] },
  { keyword: "псевдокласс", topics: ["pseudo"] },
  { keyword: "box model", topics: ["box_model"] }
];
