export const TOPIC_LABELS: Record<string, string> = {
  html_semantics: "Семантика HTML",
  forms: "Формы",
  attributes: "Атрибуты",
  block_inline: "Блочные и строчные",
  selectors: "CSS-селекторы",
  specificity: "Специфичность",
  box_model: "Box model",
  flexbox: "Flexbox",
  grid: "Grid",
  position: "Position",
  responsive: "Responsive design",
  media_queries: "Media queries",
  pseudo: "Псевдоклассы/элементы",
  cascade: "Каскад и наследование",
  units: "Единицы измерения",
  js_variables: "JS: переменные",
  js_types: "JS: типы данных",
  js_functions: "JS: функции",
  js_arrays: "JS: массивы",
  js_objects: "JS: объекты",
  js_dom: "JS: DOM",
  js_events: "JS: события",
  js_async: "JS: асинхронность"
};

export const TOPIC_LINKS: Record<string, string> = {
  html_semantics: "https://developer.mozilla.org/en-US/docs/Glossary/Semantics",
  forms: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Forms",
  attributes: "https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes",
  block_inline: "https://developer.mozilla.org/en-US/docs/Glossary/Block-level_content",
  selectors: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Basic_selectors",
  specificity: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_cascade/Specificity",
  box_model: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Box_model",
  flexbox: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Flexbox",
  grid: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Grids",
  position: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Positioning",
  responsive: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout/Responsive_Design",
  media_queries: "https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries",
  pseudo: "https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes",
  cascade: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Handling_conflicts",
  units: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics/Values_and_units",
  js_variables: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Variables",
  js_types: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures",
  js_functions: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Functions",
  js_arrays: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Arrays",
  js_objects: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Object_basics",
  js_dom: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/DOM_scripting",
  js_events: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting/Events",
  js_async: "https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS/Introducing"
};

export const VACANCY_KEYWORDS: Array<{ keyword: string; topics: string[] }> = [
  { keyword: "html", topics: ["html_semantics", "attributes"] },
  { keyword: "css", topics: ["selectors", "cascade", "units"] },
  { keyword: "bem", topics: ["selectors"] },
  { keyword: "flexbox", topics: ["flexbox"] },
  { keyword: "grid", topics: ["grid"] },
  { keyword: "адаптив", topics: ["responsive", "media_queries"] },
  { keyword: "семантик", topics: ["html_semantics"] },
  { keyword: "scss", topics: ["cascade"] },
  { keyword: "git", topics: ["attributes"] },
  { keyword: "javascript", topics: ["js_variables", "js_types", "js_functions", "js_dom", "js_events"] },
  { keyword: "js", topics: ["js_variables", "js_types", "js_functions"] },
  { keyword: "dom", topics: ["js_dom"] },
  { keyword: "event", topics: ["js_events"] },
  { keyword: "promise", topics: ["js_async"] },
  { keyword: "async", topics: ["js_async"] },
  { keyword: "форм", topics: ["forms"] },
  { keyword: "position", topics: ["position"] },
  { keyword: "media quer", topics: ["media_queries"] },
  { keyword: "псевдокласс", topics: ["pseudo"] },
  { keyword: "box model", topics: ["box_model"] }
];
